src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 */
class Annonce
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_courte;

    /**
     * @ORM\Column(type="text")
     */
    private $description_longue;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     * maxMessage="255 caracteres max")
     */
    private $ville;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEnregistrement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="annonce")
     */
    private $photos;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="annonce")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $status=2;

    
    public $moyenne;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->dateEnregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $dateEnregistrement): self
    {
        $this->dateEnregistrement = $dateEnregistrement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setAnnonce($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getAnnonce() === $this) {
                $photo->setAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAnnonce($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAnnonce() === $this) {
                $commentaire->setAnnonce(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }
}

templates/page/acceuil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}| Acceuil
{% endblock %}
{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
		{% endblock %}

{% block body %}


	<main role="main" class="container">
		<section class="row">

			{# <article class="col-md-3" style="min-width:200px;min-height:200px; border:1px solid black;"> #}
			<article class="col-md-3">
				<div class="form-group">
					<label for="exampleSelect1">Catégorie</label>
					<select class="form-control" id="exampleSelect1">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
				<div class="form-group">
					<label for="exampleSelect1">Région</label>
					<select class="form-control" id="exampleSelect1">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
				<div class="form-group">
					<label for="exampleSelect1">Membre</label>
					<select class="form-control" id="exampleSelect1">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>


				<fieldset class="form-group">
					<legend></legend>
					<label for="customRange1">Prix</label>
					<input type="range" class="custom-range" id="customRange1">
				</fieldset>
				{# <button type="submit" class="btn btn-primary">Submit</button> #}


			</article>
			<article class="col-md-9">
				<div class="form-group">
					<form method="post" action="">
						<select class="form-control" id="exampleSelect1" name="taskOption">
							<option value="first">Trier par prix(du moins cher au plus cher)</option>
							<option value="second">Trier par ordre alphabetique (A a Z)</option>
							<option value="third">Trier par date de publication( plus recentes au plus enciennes)</option>
						</select>
						{# <input type="submit" value="Recharger"/> #}
					</form>

				</div>
				<hr>
				{% if annonces %}
					{% for annonce in annonces %}
						
						<div class="row">
							{% if annonce.photos %}
								{# {{ dump(annonce.photos[0].nom)}} #}
								<a href="{{ path('fiche_annonce',{'id' : annonce.id }) }}"><div class="col-md-3">
									<img src="{{ asset("images/Upload/#{annonce.photos[0].nom}") }}" style=" width:150; height:150px;" alt=""></a>
								</div>
							{% else %}
								<a href="{{ path('fiche_annonce',{'id' : annonce.id }) }}"><img src="http://via.placeholder.com/150x150" alt=""></a>
							{% endif %}
							<div class="col-md-9">
								<a href="{{ path('fiche_annonce',{'id' : annonce.id }) }}"><h6>{{ annonce.titre }}</h6></a>
								<p>{{ annonce.descriptionCourte }}</p>
								<div class="row">
									<div class="col-md-1">
										<p>{{ annonce.user.prenom}}</p>
									</div>
									<div class="col-md-9">
										<div class="">
										{% for i in 1..annonce.moyenne[1] %}
										<i class="bi bi-star-fill text-warning"></i>
										{% endfor %}
										{% set var = 5-annonce.moyenne[1] %}
										{% if var>0 and var<1 %}
										
										<i class="bi bi-star-half text-warning"></i>
										
										{% endif %}
										{% if var>=1 %}
										{% for j in 1..var %}
										<i class="bi bi-star text-warning"></i>
										{% endfor %}
										{% endif %}
										
										{{ annonce.moyenne[1]}}/5 (sur {{ annonce.moyenne[2]}})
										
										
																																																	
										</div>
										
									</div>
									<div class="col-md-2">
										<p>{{ annonce.prix }}€</p>
									</div>


								</div>
							</div>
						</div>
						<br>
					{% endfor %}
				{% else %}
					<h4 class="text-center m-3">Pas d'annonces!</h4>
				{% endif %}
				
				<hr>
				<a href="">Voir plus</a>
			</article>

		</section>
	</main>
{% endblock %}

templates/page/add_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}| Acceuil
{% endblock %}
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
{% endblock %}

{% block body %}

	{{ form_start(formAnnonce) }}
	<main role="main" class="container">
		<h2>Déposer une annonce</h2>

		<section class="row">

			<article class="col-md-6">
				<div class="form-group">
					{{ form_row(formAnnonce.titre)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.description_courte)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.description_longue)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.prix)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.categorie)}}
				</div>

				{# <button type="submit" class="btn btn-primary">Submit</button> #}


			</article>
			<article class="col-md-6">
				<div class="form-group">
					{# {{ form_row(formAnnonce.photos)}} #}
                    {{ form_row(formAnnonce.photos,{ 'attr' : { "onChange" : "loadFile(event)" } }) }}
                    <div class="col-md-12 text-center row" id="parent">
		</div>
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.adresse)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.cp)}}
				</div>
				<div class="form-group">
					{{ form_row(formAnnonce.ville)}}
				</div>
				<div
					class="form-group">{# {{ form_row(formAnnonce.categorie)}} #}
				</div>
			</article>
			<div class=" col-md-12 d-flex justify-content-center">

				<input type="submit" value="Créer" class="btn btn-success mt-3">
			</div>
		</section>

	</main>

	{{ form_end(formAnnonce) }}
{% endblock %}
{% block javascripts %}


	<script>

        var loadFile = function(event){

            var parent = document.getElementById("parent");

            for($i = 0; $i < event.target.files.length; $i++)
            {
                parent.innerHTML += "<div class='text-center col'><img src='" + URL.createObjectURL(event.target.files[$i]) + "' style='width:80px'></div>";
            }
        }

// $.fn.modal.Constructor.prototype._enforceFocus = function() {};
// $(document).ready(function() {
//     $('#mySelect2').select2({
//         dropdownParent: $('#myModal')
//     });
// });
	</script>
{% endblock %}

templates/page/fiche_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}| Acceuil
{% endblock %}
{% block stylesheets %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
{% endblock %}

{% block body %}


	<main role="main" class="container">
		<section
			class="row">

			{# <article class="col-md-3" style="min-width:200px;min-height:200px; border:1px solid black;"> #}
			<article class="col-md-6">
				<div class="form-group">
					<h3>{{ annonce.titre}}</h3>
					<hr>
				</div>
			</article>
			<article class="col-md-6">
				<div class="form-group d-flex justify-content-end">
					<button class=" btn btn-success">
						Contacter
						{{annonce.user.nom}}</button>

				</div>
				<hr>
			</article>

		</section>
		<section
			class="row">

			{# <article class="col-md-3" style="min-width:200px;min-height:200px; border:1px solid black;"> #}
			<article class="col-md-6">
				<div class="form-group d-flex justify-content-center align-items-center" style=" height:300px;">
					<img src="{{ asset("images/Upload/#{annonce.photos[0].nom}") }}" style=" max-height:300px;" alt="{{annonce.photos[0].nom}}">

				</div>
				<hr>
			</article>
			<article class="col-md-6">
				<div class="form-group" style=" height:300px;">
					<h4>Description</h4>
					<div>
						<p>{{ annonce.descriptionLongue}}</p>
					</div>

				</div>
				<hr>
			</article>

		</section>
		<section class="row">
			<article class="col-md-12">
				<div class="d-flex justify-content-between">
					<div>
						<i class="bi bi-calendar-date"></i>
						Date de publication:
						{{ annonce.dateEnregistrement | date('d/m/Y')}}</div>
					<div>
						<i class="bi bi-person-fill"></i>
						<a href="">{{ annonce.user.nom}}</a>
					</div>
					<div>
						<i class="bi bi-cash-stack"></i>
						{{ annonce.prix}}€</div>
					<div>
						<i class="bi bi-geo-alt-fill"></i>
						Adresse:
						{{ annonce.adresse}},{{ annonce.cp}},{{ annonce.ville}}</div>
				</div>
				<hr>
			</article>

		</section>
		<section class="row">
			<article class="col-md-12">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2628.29828793615!2d2.5322296157149093!3d48.795285379281275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e60dcca14027fd%3A0x825dce7c464cabf4!2s5%20Chemin%20de%20la%20Maillarde%2C%2094430%20Chennevi%C3%A8res-sur-Marne!5e0!3m2!1sfr!2sfr!4v1619080256518!5m2!1sfr!2sfr" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
				<hr>
			</article>
		</section>
		<section >

			
				<h4>Annonces similaires
				</h4>
				<div class="row">
				{% if annoncesCat %}
					{% for  annonce in annoncesCat %}
						<div class="col-md-2">
							{% if annonce.photos %}
								{# {{ dump(annonce.photos[0].nom)}} #}
								<a href="{{ path('fiche_annonce',{'id' : annonce.id }) }}">
									<div >
										<img src="{{ asset("images/Upload/#{annonce.photos[0].nom}") }}" style=" width:150; height:150px;" alt=""></a>
								</div>
							{% else %}
								<a href="{{ path('fiche_annonce',{'id' : annonce.id }) }}"><img src="http://via.placeholder.com/150x150" alt=""></a>
							{% endif %}
						</div>
					{% endfor %}
				{% else %}
					Pas d'annonces similaires!
				{% endif %}
			</div>


		</section>
		<hr>
		<section class="row">
			{% if app.user %}
				{% if is_granted('ROLE_USER') %}
					<div class="col-md-10">
						<a href="#input">Deposer un commentaire</a>
						{% if dejaNoter ==false and app.user != annonce.user %}
							|
							<a href="#input">Noter {{annonce.user.nom}}</a>
						{% endif %}
					</div>
				{% endif %}
			{% endif %}
			<div class="col-md-2">
				<a href="">Retour vers annonces</a>
			</div>

			<hr>
		</section>
		<hr>
		<section class="row">

			<div class="col-md-10 mx-auto">
				<h4>Commentaires:
				</h4>
				<div class="alert alert-success  mx-auto">


					{% for comment in comments %}
						<div class="form-group">
							<div>{{ comment.user.nom }}:</div>
							<div>{{ comment.commentaire }}
								-
								{{ comment.dateEnregistrement | date('d/m/Y')}}</div>
						</div>
					{% endfor %}
					{{ form_start(formC) }}
					{{ form_row(formC.commentaire) }}
					<div id="input">
						<input type="submit" value="Enregistrer" class="btn btn-success bg-primary mt-3">
					</div>
					{{ form_end(formC) }}
				</div>
			</div>
			{# <div class="col-md-10 mx-auto">
						<div class="alert alert-success col-6 mx-auto">
						
						</div>
						</div> #}
			<hr>
		</section>
		{% if dejaNoter ==false and app.user != annonce.user %}
		<section class="row">

			<div class="col-md-10 mx-auto">
				<h4>Noter
					{{annonce.user.nom}}:
				</h4>
				<div class="alert alert-success  mx-auto">
				{{ form_start(formNote) }}
					<div class="form-group">
					
					{{ form_row(formNote.note) }}
					</div>
					<div class="form-group">
					{{ form_row(formNote.avis) }}
					</div>
					<div  class="form-group" id="inputNote">
						<input type="submit" value="Envoyer" class="btn btn-success bg-primary mt-3">
					</div>
					
					
					{{ form_end(formNote) }}
				</div>
			</div>
			{# <div class="col-md-10 mx-auto">
						<div class="alert alert-success col-6 mx-auto">
						
						</div>
						</div> #}
			<hr>
		</section>
		{% endif %}

	</main>
{% endblock %}